 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: blip2_vicuna_instruct
  model_type: vicuna7b
  load_pretrained: True
  pretrained: /mnt/petrelfs/songmingyang/songmingyang/model/mm/instruct_blip/instruct_blip_7b

datasets:
  palo: # name of the dataset builder
    data_type: images # [images|videos|features] we use features in this case for extracted video features
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          storage: /mnt/petrelfs/songmingyang/songmingyang/data/mm/annotation/palo_train_data/palo_multilingual_dataset.json
      images:
        storage: /mnt/petrelfs/songmingyang/songmingyang/data/mm/imgs


run:
  task: vqa
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 0
  warmup_lr: 1e-8
  warmup_steps: 1000
  weight_decay: 0.05
  max_epoch: 1
  batch_size_train: 16
  batch_size_eval: 1
  num_workers: 8
  accum_grad_iters: 1

  max_len: 10
  min_len: 1
  num_beams: 5
  inference_method: "generate"
  length_penalty: -1.

  seed: 42
  output_dir: "/mnt/petrelfs/songmingyang/songmingyang/runs/llava/sft/checkpoints/instruct_blip_vicuna7b_palo"

  amp: True
  resume_ckpt_path: null

  evaluate: True
  train_splits: ["train"]
  # valid_splits: ["test"]


  device: "cuda"
  world_size: 8
  dist_url: "env://"
  distributed: True
  save_freq: -1 # save epoch every xxx epochs -1 only save last and best. 
  val_freq: 1
